spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  server:
    max-http-header-size: 1000MB
  tomcat:
    max-swallow-size: -1
    max-post-size: 1000MB


  datasource:
    url: jdbc:postgresql://localhost:5432/upgrade_education
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver

    main:
      web-application-type: none
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

pring:
  main:
    web-application-type=reactive:
